In [1]:
import pandas as pd

df = pd.read_csv("telco_churn.csv")
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [2]:
df.shape

(3333, 20)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   3333 non-null   str
 1   Account length          3333 non-null   int64
 2   Area code               3333 non-null   int64
 3   International plan      3333 non-null   str
 4   Voice mail plan         3333 non-null   str
 5   Number vmail messages   3333 non-null   int64
 6   Total day minutes       3323 non-null   float64
 7   Total day calls         3323 non-null   float64
 8   Total day charge        3315 non-null   float64
 9   Total eve minutes       3324 non-null   float64
 10  Total eve calls         3325 non-null   float64
 11  Total eve charge        3333 non-null   float64
 12  Total night minutes     3333 non-null   float64
 13  Total night calls       3332 non-null   float64
 14  Total night charge      3333 non-null   float64
 15  Total intl minutes      3333 non-null   float64
 16  Total intl calls        3333 non-null   int64
 17  Total intl charge       3328 non-null   float64
 18  Customer service calls  3328 non-null   float64
 19  Churn                   3325 non-null   object
dtypes: float64(12), int64(4), object(1), str(3)
memory usage: 541.7+ KB

In [4]:
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.000000,3333.000000,3333.000000,3323.000000,3323.000000,3315.000000,3324.000000,3325.000000,3333.000000,3333.000000,3332.000000,3333.000000,3333.000000,3333.000000,3328.000000,3328.000000
mean,101.064806,437.182418,8.099010,179.787150,100.456214,30.557831,201.033935,100.110677,17.083540,200.872037,100.115246,9.039325,10.237294,4.479448,2.764588,1.563101
std,39.822106,42.371290,13.688365,54.419625,20.057356,9.255987,50.676652,19.932115,4.310668,50.573847,19.566710,2.275873,2.791840,2.461214,0.754086,1.315870
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.420000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.500000,114.000000,36.780000,235.325000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [5]:
df.isnull().sum()

State                      0
Account length             0
Area code                  0
International plan         0
Voice mail plan            0
Number vmail messages      0
Total day minutes         10
Total day calls           10
Total day charge          18
Total eve minutes          9
Total eve calls            8
Total eve charge           0
Total night minutes        0
Total night calls          1
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          5
Customer service calls     5
Churn                      8
dtype: int64

In [6]:
df["State"]

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: str

In [7]:
df[["State", "International plan", "Churn"]].head()

  State International plan  Churn
0    KS                 No  False
1    OH                 No  False
2    NJ                 No  False
3    OH                Yes  False
4    OK                Yes  False

In [8]:
df[df["State"] == "OH"].head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
152,OH,65,408,No,No,0,187.9,116.0,31.94,157.6,117.0,13.40,227.3,86.0,10.23,7.5,6,2.03,1.0,False
156,OH,83,415,No,No,0,337.4,120.0,57.36,227.4,116.0,19.33,153.9,114.0,6.93,15.8,7,4.27,0.0,True
231,OH,63,415,Yes,Yes,36,199.0,110.0,33.83,291.3,111.0,24.76,197.6,92.0,8.89,11.0,6,2.97,1.0,False

In [9]:
df[df["Customer service calls"] > 3].head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
21,CO,77,408,No,No,0,NaN,NaN,NaN,169.9,121.0,14.44,209.6,64.0,9.43,5.7,6,1.54,5.0,True
48,ID,119,415,No,No,0,159.1,114.0,27.05,231.3,117.0,19.66,143.2,91.0,6.44,8.8,3,2.38,5.0,True

In [10]:
df.iloc[0]

State                        KS
Account length              128
Area code                   415
International plan           No
Voice mail plan             Yes
Number vmail messages        25
Total day minutes         265.1
Total day calls           110.0
Total day charge          45.07
Total eve minutes         197.4
Total eve calls            99.0
Total eve charge          16.78
Total night minutes       244.7
Total night calls          91.0
Total night charge        11.01
Total intl minutes         10.0
Total intl calls              3
Total intl charge           2.7
Customer service calls      1.0
Churn                     False
Name: 0, dtype: object

In [11]:
df.iloc[0:5, 0:3]

  State  Account length  Area code
0    KS             128        415
1    OH             107        415
2    NJ             137        415
3    OH              84        408
4    OK              75        415

In [12]:
df["Churn"].value_counts()

Churn
False    2842
True      483
Name: count, dtype: int64

In [13]:
df["Total day minutes"].mean()

np.float64(179.78715016551308)

In [14]:
df.groupby("Churn")["Total day minutes"].mean()

Churn
False    175.172336
True     206.952599
Name: Total day minutes, dtype: float64

In [15]:
df_clean = df.dropna()
df_clean.shape

(3307, 20)

In [16]:
df_clean.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [17]:
df_filled = df.copy()
df_filled["Total day minutes"] = df_filled["Total day minutes"].fillna(
    df_filled["Total day minutes"].mean()
)
df_filled["Total day minutes"].isnull().sum()

np.int64(0)

In [18]:
df_clean = df_clean.copy()
df_clean["Total minutes"] = (
    df_clean["Total day minutes"]
    + df_clean["Total eve minutes"]
    + df_clean["Total night minutes"]
    + df_clean["Total intl minutes"]
)

df_clean[["State", "Total minutes"]].head()

  State  Total minutes
0    KS          717.2
1    OH          625.2
2    NJ          539.4
3    OH          564.8
4    OK          512.0

In [19]:
df_clean.sort_values("Total minutes", ascending=False).head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,Total minutes
985,NY,64,415,Yes,No,0,346.8,55.0,58.96,249.5,...,21.21,275.4,102.0,12.39,13.3,9,3.59,1.0,True,885.0
289,OK,89,510,No,No,0,303.9,95.0,51.66,260.9,...,22.18,312.1,89.0,14.04,5.3,3,1.43,1.0,True,882.2
3205,MS,111,408,No,No,0,294.7,90.0,50.10,294.6,...,25.04,260.1,121.0,11.70,10.8,3,2.92,1.0,True,860.2
914,MO,179,510,No,No,0,287.3,123.0,48.84,288.0,...,24.48,266.0,112.0,11.97,10.5,4,2.84,0.0,True,851.8
1645,CT,95,415,No,Yes,36,283.1,112.0,48.13,286.2,...,24.33,261.7,129.0,11.78,11.3,3,3.05,3.0,False,842.3

In [20]:
df_without_total = df_clean.drop(columns=["Total minutes"])
df_without_total.shape

(3307, 20)

In [21]:
df_clean["Day minutes in hours"] = df_clean["Total day minutes"].apply(
    lambda minutes: minutes / 60
)

df_clean[["Total day minutes", "Day minutes in hours"]].head()

   Total day minutes  Day minutes in hours
0              265.1              4.418333
1              161.6              2.693333
2              243.4              4.056667
3              299.4              4.990000
4              166.7              2.778333

In [22]:
df_clean.to_csv("telco_churn_cleaned.csv", index=False)

In [23]:
tempdict = {
    "col1": [1, 2, 3],
    "col2": [4, 5, 6],
    "col3": [7, 8, 9]
}
dictdf = pd.DataFrame.from_dict(tempdict)
dictdf.head()

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

In [24]:
df.tail(15)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3318,OK,52,415,No,No,0,124.9,131.0,21.23,300.5,118.0,25.54,192.5,106.0,8.66,11.6,4,3.13,2.0,False
3319,WY,89,415,No,No,0,115.4,99.0,19.62,209.9,115.0,17.84,280.9,112.0,12.64,15.9,6,4.29,3.0,False
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True
3321,VT,60,415,No,No,0,193.9,118.0,32.96,85.0,110.0,7.23,210.1,134.0,9.45,13.2,8,3.56,3.0,False
3322,MD,62,408,No,No,0,321.1,105.0,54.59,265.5,122.0,22.57,180.5,72.0,8.12,11.5,2,3.11,4.0,True
3323,IN,117,415,No,No,0,118.4,126.0,20.13,249.3,97.0,21.19,227.0,56.0,10.22,13.6,3,3.67,5.0,True
3324,WV,159,415,No,No,0,169.8,114.0,28.87,197.7,105.0,16.80,193.7,82.0,8.72,11.6,4,3.13,1.0,False
3325,OH,78,408,No,No,0,193.4,99.0,32.88,116.9,88.0,9.94,243.3,109.0,10.95,9.3,4,2.51,2.0,False
3326,OH,96,415,No,No,0,106.6,128.0,18.12,284.8,87.0,24.21,178.9,92.0,8.05,14.9,7,4.02,1.0,False
3327,SC,79,415,No,No,0,134.7,98.0,22.90,189.7,68.0,16.12,221.4,128.0,9.96,11.8,5,3.19,2.0,False
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [25]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='str')

In [26]:
df.dtypes

State                         str
Account length              int64
Area code                   int64
International plan            str
Voice mail plan               str
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

In [28]:
df.describe(include=["object", "str"])

       State International plan Voice mail plan  Churn
count   3333               3333            3333   3325
unique    51                  2               2      2
top       WV                 No              No  False
freq     106               3010            2411   2842

In [29]:
df["Churn"].unique()

array([False, nan, True], dtype=object)

In [30]:
df[(df["International plan"] == "No") & (df["Churn"] == True)]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
21,CO,77,408,No,No,0,NaN,NaN,NaN,169.9,121.0,14.44,209.6,64.0,9.43,5.7,6,1.54,5.0,True
33,AZ,12,408,No,No,0,249.6,118.0,NaN,NaN,NaN,21.45,280.2,90.0,12.61,11.8,3,3.19,1.0,True
48,ID,119,415,No,No,0,159.1,114.0,27.05,231.3,117.0,19.66,143.2,91.0,6.44,8.8,3,2.38,5.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280,AR,76,408,No,No,0,107.3,140.0,18.24,238.2,133.0,20.25,271.8,116.0,12.23,10.0,3,2.70,4.0,True
3287,KS,170,415,No,Yes,42,199.5,119.0,33.92,135.0,90.0,11.48,184.6,49.0,8.31,10.9,3,2.94,4.0,True
3301,CA,84,415,No,No,0,280.0,113.0,47.60,202.2,90.0,17.19,156.8,103.0,7.06,10.4,4,2.81,0.0,True
3322,MD,62,408,No,No,0,321.1,105.0,54.59,265.5,122.0,22.57,180.5,72.0,8.12,11.5,2,3.11,4.0,True
3323,IN,117,415,No,No,0,118.4,126.0,20.13,249.3,97.0,21.19,227.0,56.0,10.22,13.6,3,3.67,5.0,True

In [31]:
df.iloc[14, -1]

False

In [32]:
state = df.copy()
state.set_index("State", inplace=True)
state.loc["OH"]

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
OH,65,408,No,No,0,187.9,116.0,31.94,157.6,117.0,13.40,227.3,86.0,10.23,7.5,6,2.03,1.0,False
OH,83,415,No,No,0,337.4,120.0,57.36,227.4,116.0,19.33,153.9,114.0,6.93,15.8,7,4.27,0.0,True
OH,63,415,Yes,Yes,36,199.0,110.0,33.83,291.3,111.0,24.76,197.6,92.0,8.89,11.0,6,2.97,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
OH,160,415,No,No,0,206.3,66.0,35.07,241.1,109.0,20.49,227.8,102.0,10.25,11.7,6,3.16,0.0,False
OH,88,408,No,No,0,274.6,105.0,46.68,161.1,121.0,13.69,194.4,123.0,8.75,9.2,4,2.48,2.0,False
OH,106,415,No,Yes,30,220.1,105.0,37.42,222.2,109.0,18.89,158.4,96.0,7.13,13.1,8,3.54,0.0,False
OH,78,408,No,No,0,193.4,99.0,32.88,116.9,88.0,9.94,243.3,109.0,10.95,9.3,4,2.51,2.0,False
OH,96,415,No,No,0,106.6,128.0,18.12,284.8,87.0,24.21,178.9,92.0,8.05,14.9,7,4.02,1.0,False

In [33]:
tutorial_df = df.dropna().copy()
tutorial_df["New Column"] = (
    tutorial_df["Total night minutes"]
    + tutorial_df["Total intl minutes"]
)
tutorial_df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,New Column
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,254.7
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,268.1
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,174.8
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,203.5
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,197.0

In [34]:
tutorial_df["New Column"] = 100
tutorial_df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,New Column
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,100
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,100
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,100
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,100
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,100

In [35]:
tutorial_df.iloc[0, -1] = 10
tutorial_df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,New Column
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,10
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,100
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,100
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,100
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,100

In [36]:
tutorial_df["Churn Binary"] = tutorial_df["Churn"].apply(
    lambda x: 1 if x == True else 0
)
tutorial_df[["Churn", "Churn Binary"]].head()

   Churn  Churn Binary
0  False             0
1  False             0
2  False             0
3  False             0
4  False             0

In [37]:
tutorial_df.drop("Area code", axis=1).head()

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,...,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,New Column,Churn Binary
0,KS,128,No,Yes,25,265.1,110.0,45.07,197.4,99.0,...,244.7,91.0,11.01,10.0,3,2.70,1.0,False,10,0
1,OH,107,No,Yes,26,161.6,123.0,27.47,195.5,103.0,...,254.4,103.0,11.45,13.7,3,3.70,1.0,False,100,0
2,NJ,137,No,No,0,243.4,114.0,41.38,121.2,110.0,...,162.6,104.0,7.32,12.2,5,3.29,0.0,False,100,0
3,OH,84,Yes,No,0,299.4,71.0,50.90,61.9,88.0,...,196.9,89.0,8.86,6.6,7,1.78,2.0,False,100,0
4,OK,75,Yes,No,0,166.7,113.0,28.34,148.3,122.0,...,186.9,121.0,8.41,10.1,3,2.73,3.0,False,100,0

In [39]:
tutorial_df.to_csv("output.csv", index=False)

In [40]:
json_output = tutorial_df.to_json()
print(json_output[:500])

{"State":{"0":"KS","1":"OH","2":"NJ","3":"OH","4":"OK","5":"AL","7":"MO","8":"LA","9":"WV","10":"IN","11":"RI","23":"SC","24":"VA","25":"NE","26":"WY","27":"MT","28":"MO","30":"IL","39":"NJ","40":"GA","41":"MD","42":"AR","43":"ID","44":"WI","45":"OR","46":"MI","47":"DE","48":"ID","49":"WY","50":"IA","51":"IN","52":"VA","53":"UT","54":"WY","55":"IN","56":"CO","57":"CO","58":"WI","59":"OK","60":"ID","61":"CA","62":"MN","63":"SD","64":"NC","65":"WA","66":"WY","67":"MN","68":"UT","69":"TX","70":"NJ"

In [41]:
html_output = tutorial_df.to_html()
print(html_output[:500])

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>State</th>
      <th>Account length</th>
      <th>Area code</th>
      <th>International plan</th>
      <th>Voice mail plan</th>
      <th>Number vmail messages</th>
      <th>Total day minutes</th>
      <th>Total day calls</th>
      <th>Total day charge</th>
      <th>Total eve minutes</th>
      <th>Total eve calls</th>
      <th>Total eve charge</th>
      <th>Total night minutes</

In [42]:
del tutorial_df